language: rust

cache: cargo

matrix:
  rust:
    - stable
    - beta
    - nightly
  env:
    - JOB="test"
    - JOB="bench"
    - JOB="wasm"
  exclude:
    - rust: stable
      env: JOB="bench"
    - rust: beta
      env: JOB="bench"
    - rust: stable
      env: JOB="wasm"
    - rust: beta
      env: JOB="wasm"

script:
  - ./ci/script.sh
